# 🐼 **AUPP Data Science Club**

## **Week 2: NumPy, Pandas, and Data Exploration**

## Data Exploration

💝 We will be working with the [Valentine's Day Gift & Satisfaction Dataset 2025](https://www.kaggle.com/datasets/eunglaimeng/valentines-day-gift-and-satisfaction-dataset-2025?), which is a **synthetic dataset** designed for doing basic data exploration, featuring 670 romantic gift-giving scenarios with satisfaction ratings.

---

![valentine-poster.png](https://github.com/AUPP-Data-Science-Club/week2-numpy-pandas-and-data-exploration/blob/main/valentine-poster.png?raw=True)


---

### Download Dataset

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("eunglaimeng/valentines-day-gift-and-satisfaction-dataset-2025")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\eungl\.cache\kagglehub\datasets\eunglaimeng\valentines-day-gift-and-satisfaction-dataset-2025\versions\3

In [ ]:
%ls {path}

### Import Libraries

In [3]:
# Import NumPy and Pandas
import pandas as pd

In [4]:
# Read the downloaded dataset
data = pd.read_csv(path + "/valentine_gifts_satisfaction.csv")

data.head()

,id,receiver_gender,receiver_age,relationship_type,months_together,gift_item,gift_category,price,flower_count,days_prepared,receiver_satisfaction
0,1,Non-binary,31,Married,96,Necklace,Jewelry,45.51,24,7,4
1,2,Female,33,Engaged,65,Labubu Doll,Collectibles,72.56,0,7,5
2,3,Male,29,Dating,23,Necklace,Jewelry,37.05,0,2,4
3,4,Non-binary,39,Married,112,Necklace,Jewelry,124.86,24,1,3
4,5,Male,47,Dating,35,Dubai Chocolate,Sweets,27.71,0,5,4

### Data Explanation

| Column | Type | Description |
|--------|------|-------------|
| `id` | Integer | Unique identifier (1-670) |
| `receiver_gender` | String | Gender of gift receiver (Female, Male, Non-binary) |
| `receiver_age` | Integer | Age of receiver (18-60 years) |
| `relationship_type` | String | Type of relationship (Dating, Married, First Date, Engaged, Complicated) |
| `months_together` | Integer | Duration of relationship in months (0-357) |
| `gift_item` | String | Specific gift given (18 different items) |
| `gift_category` | String | Category of gift (Sweets, Jewelry, Luxury, Collectibles, Gaming, Sentimental) |
| `price` | Float | Price of gift in USD ($5-$500) |
| `flower_count` | Integer | Number of flowers included (0, 1, 3, 6, 12, 24, 50, 67) |
| `days_prepared` | Integer | Days spent preparing the gift (0-200) |
| `receiver_satisfaction` | Integer | Satisfaction rating (1-5 scale, 1=very unhappy, 5=very happy) |

### Understanding the data

- find the shape of `data`
- get key information from our `data` using `.info()`
- get statistical summary of the `data` using `.describe()` 
- drop `id` column

In [7]:
print("Shape of data:", data.shape)

Shape of data: (670, 11)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670 entries, 0 to 669
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     670 non-null    int64
 1   receiver_gender        670 non-null    object
 2   receiver_age           670 non-null    int64
 3   relationship_type      670 non-null    object
 4   months_together        670 non-null    int64
 5   gift_item              670 non-null    object
 6   gift_category          670 non-null    object
 7   price                  670 non-null    float64
 8   flower_count           670 non-null    int64
 9   days_prepared          670 non-null    int64
 10  receiver_satisfaction  670 non-null    int64
dtypes: float64(1), int64(6), object(4)
memory usage: 57.7+ KB

In [9]:
print("Statistical Summary of data:")
data.describe()

Statistical Summary of data:

,id,receiver_age,months_together,price,flower_count,days_prepared,receiver_satisfaction
count,670.000000,670.000000,670.000000,670.000000,670.000000,670.000000,670.000000
mean,335.500000,34.164179,68.934328,86.003134,13.777612,22.980597,4.000000
std,193.556624,8.321092,81.018342,94.621062,17.624630,31.750493,0.807291
min,1.000000,18.000000,0.000000,5.260000,0.000000,0.000000,2.000000
25%,168.250000,28.000000,13.250000,25.170000,1.000000,4.000000,3.250000
50%,335.500000,34.000000,36.000000,42.065000,6.000000,9.000000,4.000000
75%,502.750000,40.000000,96.000000,111.932500,24.000000,36.000000,5.000000
max,670.000000,56.000000,357.000000,482.880000,67.000000,199.000000,5.000000

In [10]:
data = data.drop(columns='id')

1. What is the proportion of receiver's gender?

In [11]:
data['receiver_gender'].value_counts()

receiver_gender
Female        350
Male          240
Non-binary     80
Name: count, dtype: int64

2. How many unique gifts are there? What are they?

In [14]:
n_unique_gifts = data['gift_item'].nunique()
print(f"There are {n_unique_gifts} unique gifts")

data['gift_item'].unique()

There are 18 unique gifts

array(['Necklace', 'Labubu Doll', 'Dubai Chocolate', 'Perfume',
       'Teddy Bear', 'AirPods', 'Scented Candles', 'Cookies', 'Watch',
       'Roblox Robux', 'Earring', 'Stanley Cup', 'Ring', 'Handmade Card',
       'MLBB Skin', 'Gojo Plush', 'Book', 'Concert Tickets'], dtype=object)

3. What gift category were gifted the most? Which one were gifted the least?

In [26]:
# Use .value_counts() to show the occurences of each elements
data['gift_category'].value_counts()

gift_category
Jewelry         142
Collectibles    140
Sweets          138
Sentimental     121
Luxury           71
Gaming           58
Name: count, dtype: int64

In [36]:
most_gifted = data['gift_category'].value_counts().idxmax() # .idxmax() returns the index of the maximum value
least_gifted = data['gift_category'].value_counts().idxmin()

print(f"Most Gifted: {most_gifted}\nMost Gifted: {least_gifted}")

Most Gifted: Jewelry
Most Gifted: Gaming

4. What was the most popular gift item?

In [25]:
data['gift_item'].value_counts()

gift_item
Dubai Chocolate    107
Labubu Doll         88
Necklace            84
Ring                33
MLBB Skin           31
Cookies             30
Teddy Bear          29
Book                27
Roblox Robux        27
Scented Candles     27
Stanley Cup         27
Perfume             26
Gojo Plush          25
Earring             25
AirPods             24
Watch               22
Handmade Card       22
Concert Tickets     16
Name: count, dtype: int64

5. What was the average price spent on Labubu Doll?

In [47]:
data[data['gift_item'] == 'Labubu Doll']['price'].mean()

np.float64(47.97295454545454)

6. On average, what item is the most expensive gift?

In [50]:
data.groupby('gift_item')['price'].mean().sort_values(ascending=False)

gift_item
Ring               292.571515
Watch              286.488182
AirPods            199.397083
Concert Tickets    157.623125
Necklace           154.348095
Earring            132.236400
Perfume            117.629615
Roblox Robux        55.168148
Labubu Doll         47.972955
Gojo Plush          45.170800
Stanley Cup         41.175185
Teddy Bear          38.242069
Scented Candles     29.670000
Book                27.639259
MLBB Skin           27.102258
Dubai Chocolate     25.762897
Handmade Card       15.920455
Cookies             15.730000
Name: price, dtype: float64

7. Find all gifts given to people aged 40 or older

In [51]:
data[data['receiver_age'] >= 40]['gift_item'].value_counts()

gift_item
Dubai Chocolate    34
Necklace           23
Labubu Doll        22
MLBB Skin          13
Ring               11
Scented Candles     9
Teddy Bear          8
Earring             7
Book                7
Cookies             7
Stanley Cup         6
AirPods             6
Roblox Robux        6
Watch               4
Gojo Plush          4
Handmade Card       3
Concert Tickets     3
Perfume             3
Name: count, dtype: int64

8. How many people did not get their partner a flower?

In [60]:
(data['flower_count'] == 0).sum()

# orrrr
# len(data[data['flower_count'] == 0])

np.int64(145)

9. Find all receivers who received a gift of less than $10 in price, and still fully satisfied with their gift.

In [68]:
data[(data['price'] < 10) & (data['receiver_satisfaction'] == 5)]
# Note: don't forget to wrap each condition in a parenthesis ()
# Also, Pandas support bit-wise operations (& |)

,receiver_gender,receiver_age,relationship_type,months_together,gift_item,gift_category,price,flower_count,days_prepared,receiver_satisfaction
54,Male,45,First Date,0,Cookies,Sweets,8.81,6,11,5
60,Female,38,Married,87,Handmade Card,Sentimental,5.40,24,4,5
87,Female,34,Dating,39,Cookies,Sweets,8.79,50,6,5
138,Female,24,First Date,0,MLBB Skin,Gaming,5.56,50,3,5
410,Male,22,Dating,28,Handmade Card,Sentimental,5.97,12,11,5
583,Female,34,Dating,24,Handmade Card,Sentimental,7.56,12,29,5
648,Male,32,Dating,24,Handmade Card,Sentimental,8.79,1,60,5

10. Display all the data for the couple who have been together for over 300 months

In [69]:
data[data['months_together'] > 300]

,receiver_gender,receiver_age,relationship_type,months_together,gift_item,gift_category,price,flower_count,days_prepared,receiver_satisfaction
34,Male,46,Married,319,Dubai Chocolate,Sweets,21.28,12,24,4
119,Female,48,Married,357,Earring,Jewelry,197.81,12,6,5
127,Male,46,Married,347,Earring,Jewelry,67.48,0,7,4
197,Male,49,Married,306,Dubai Chocolate,Sweets,15.77,0,21,3
226,Male,50,Married,330,Dubai Chocolate,Sweets,33.47,0,133,4
253,Female,46,Married,315,Book,Sentimental,24.98,0,6,4
284,Female,47,Married,309,Earring,Jewelry,249.57,24,5,5
376,Female,48,Married,333,Dubai Chocolate,Sweets,32.20,3,0,4
469,Female,50,Married,311,Ring,Jewelry,399.19,50,45,4
536,Female,50,Married,344,MLBB Skin,Gaming,49.55,24,1,3
552,Female,45,Married,357,Dubai Chocolate,Sweets,25.44,0,2,4
571,Female,47,Married,306,MLBB Skin,Gaming,23.19,6,31,2
579,Female,47,Married,321,Teddy Bear,Sentimental,24.90,12,23,4
615,Female,54,Married,344,Perfume,Luxury,180.01,3,4,4
629,Male,46,Married,307,Necklace,Jewelry,185.59,0,7,5

11. Calculate the average satisfaction for each gift item

In [74]:
data.groupby('gift_item')['receiver_satisfaction'].mean()

gift_item
AirPods            4.125000
Book               3.851852
Concert Tickets    4.812500
Cookies            3.733333
Dubai Chocolate    4.084112
Earring            4.000000
Gojo Plush         4.320000
Handmade Card      4.500000
Labubu Doll        4.329545
MLBB Skin          3.451613
Necklace           3.869048
Perfume            3.730769
Ring               3.969697
Roblox Robux       3.629630
Scented Candles    3.777778
Stanley Cup        3.962963
Teddy Bear         3.758621
Watch              3.954545
Name: receiver_satisfaction, dtype: float64

12. (Hard) Find the couple who have been together the longest, and still not engaged or married yet
> Hint: 
> - Filter using `~` (NOT operator) and `.isin()`
> - Use `.nlargest(n, columns, keep(optional))` to find the first `n` rows with the largest values 
>    > - n: number of rows to return
>    > - columns: column name
>    > - keep (optional): whether to retrieve the `first`, `last`, or retrieve `all`, in case of duplicates

In [86]:
data[~data['relationship_type'].isin(['Married', 'Engaged'])].nlargest(n=1, columns='months_together', keep='all')

,receiver_gender,receiver_age,relationship_type,months_together,gift_item,gift_category,price,flower_count,days_prepared,receiver_satisfaction
14,Male,27,Dating,47,AirPods,Luxury,238.99,12,25,4
30,Female,27,Dating,47,Necklace,Jewelry,202.17,12,10,5
132,Male,33,Dating,47,Earring,Jewelry,229.23,0,8,5
213,Male,24,Dating,47,Dubai Chocolate,Sweets,30.62,24,51,4
286,Female,23,Dating,47,Labubu Doll,Collectibles,75.35,6,0,4
394,Female,35,Dating,47,Gojo Plush,Collectibles,23.13,6,31,5
626,Female,32,Dating,47,Labubu Doll,Collectibles,57.47,24,4,5
666,Male,36,Dating,47,Scented Candles,Sentimental,38.59,0,5,4

### Let's work with File Handling

1. Open the file `receiver_names_emails.csv`

In [87]:
personal_data = pd.read_csv(path + "/receiver_names_emails.csv")

personal_data.head()

      receiver_name             receiver_email
0     Lauren Torres   lauren.torres@icloud.com
1  Andrewlee Turner        andrewlee@yahoo.com
2       Avery Adams    avery_adams@outlook.com
3      Sarah Torres  sarah.torres@tutanota.com
4        Ryan Baker         ryan3715@gmail.com

2. Combine `personal_data` with our main `data` to a new DataFrame called `new_data`

In [93]:
new_data = pd.concat([data, personal_data], axis=1)

new_data.head()

,receiver_gender,receiver_age,relationship_type,months_together,gift_item,gift_category,price,flower_count,days_prepared,receiver_satisfaction,receiver_name,receiver_email
0,Non-binary,31,Married,96,Necklace,Jewelry,45.51,24,7,4,Lauren Torres,lauren.torres@icloud.com
1,Female,33,Engaged,65,Labubu Doll,Collectibles,72.56,0,7,5,Andrewlee Turner,andrewlee@yahoo.com
2,Male,29,Dating,23,Necklace,Jewelry,37.05,0,2,4,Avery Adams,avery_adams@outlook.com
3,Non-binary,39,Married,112,Necklace,Jewelry,124.86,24,1,3,Sarah Torres,sarah.torres@tutanota.com
4,Male,47,Dating,35,Dubai Chocolate,Sweets,27.71,0,5,4,Ryan Baker,ryan3715@gmail.com

3. Find all receivers with the last name 'Lee'

In [98]:
new_data[new_data['receiver_name'].str.contains('Lee')]

,receiver_gender,receiver_age,relationship_type,months_together,gift_item,gift_category,price,flower_count,days_prepared,receiver_satisfaction,receiver_name,receiver_email
21,Female,22,Dating,22,Labubu Doll,Collectibles,63.83,12,7,5,Aadams Lee,aadams@gmail.com
212,Male,32,Dating,11,Necklace,Jewelry,152.07,0,8,4,Madison Lee,madison.lee@gmail.com
257,Non-binary,23,Dating,23,AirPods,Luxury,202.11,50,4,5,Khernandez Lee,khernandez@icloud.com
399,Female,52,Married,120,Dubai Chocolate,Sweets,28.92,6,49,4,Kwright Lee,kwright@icloud.com
427,Female,36,Dating,42,Scented Candles,Sentimental,17.97,0,2,3,Madison Lee,madison1938@outlook.com
457,Female,19,First Date,0,Dubai Chocolate,Sweets,22.07,0,48,3,Charlie Lee,charlie2259@yahoo.com
648,Male,32,Dating,24,Handmade Card,Sentimental,8.79,1,60,5,Emma Lee,emma.lee@gmail.com

4. how many receivers uses `gmail` as their email address

In [102]:
len(new_data[new_data['receiver_email'].str.contains('gmail')])

297

5. Find all receivers who has a number in their email address

In [ ]:
new_data[new_data['receiver_email'].str.contains('[0,9]')]
# regex=True may be needed

,receiver_gender,receiver_age,relationship_type,months_together,gift_item,gift_category,price,flower_count,days_prepared,receiver_satisfaction,receiver_name,receiver_email
25,Non-binary,22,Dating,39,Cookies,Sweets,9.54,1,10,4,Jessica Turner,jessica799@yahoo.com
32,Female,43,Married,153,Labubu Doll,Collectibles,53.16,1,3,4,Kyle Evans,kyle8074@gmail.com
50,Non-binary,39,Dating,34,Dubai Chocolate,Sweets,24.63,67,0,4,Sam Hall,sam798@gmail.com
58,Female,32,Complicated,44,Earring,Jewelry,180.82,0,5,4,Avery Turner,avery4610@yahoo.com
78,Male,23,First Date,0,Teddy Bear,Sentimental,41.21,12,35,5,Heartkyle Adams,heartkyle49@protonmail.com
...,...,...,...,...,...,...,...,...,...,...,...,...
629,Male,46,Married,307,Necklace,Jewelry,185.59,0,7,5,Sweethannah Walker,sweethannah93@gmail.com
638,Female,31,Dating,14,Dubai Chocolate,Sweets,33.42,3,15,4,Casey Roberts,casey170@gmail.com
642,Female,34,First Date,0,Cookies,Sweets,15.44,50,6,5,Taylor Jackson,taylor8900@yahoo.com
655,Non-binary,36,Engaged,23,Perfume,Luxury,73.79,24,178,4,Tyler King,tyler5406@gmail.com
669,Female,37,First Date,0,Concert Tickets,Sentimental,149.33,1,36,5,David Roberts,david9467@yahoo.com